// Indoor Location Data - Auto-generated
// Total entries: 123

export const indoorLocationData = {
  "A107": {
    "id": "A107",
    "name": "Metrology Lab",
    "parentBuilding": "ABlock",
    "floor": 0,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Metrology-Lab",
    "blockName": "A-Block"
  },
  "A111": {
    "id": "A111",
    "name": "Mechatronics Lab",
    "parentBuilding": "ABlock",
    "floor": 0,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Mechatronics-Lab",
    "blockName": "A-Block"
  },
  "A213": {
    "id": "A213",
    "name": "Communication Lab",
    "parentBuilding": "ABlock",
    "floor": 1,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Comm-Lab",
    "blockName": "A-Block"
  },
  "A307": {
    "id": "A307",
    "name": "MATLAB Lab A307",
    "parentBuilding": "ABlock",
    "floor": 2,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "MAT-Lab",
    "blockName": "A-Block"
  },
  "A308": {
    "id": "A308",
    "name": "MATLAB Lab A308",
    "parentBuilding": "ABlock",
    "floor": 2,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "MAT-Lab",
    "blockName": "A-Block"
  },
  "A310": {
    "id": "A310",
    "name": "MATLAB Lab A310",
    "parentBuilding": "ABlock",
    "floor": 2,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "MAT-Lab",
    "blockName": "A-Block"
  },
  "A414": {
    "id": "A414",
    "name": "Operating Systems Lab",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "OS-Lab",
    "blockName": "A-Block"
  },
  "A306": {
    "id": "A306",
    "name": "Science and Humanities",
    "parentBuilding": "ABlock",
    "floor": 2,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A306",
    "blockName": "A-Block"
  },
  "A403": {
    "id": "A403",
    "name": "English Faculty Room",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A403",
    "blockName": "A-Block"
  },
  "A406": {
    "id": "A406",
    "name": "English Faculty Room A406",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A406",
    "blockName": "A-Block"
  },
  "A105": {
    "id": "A105",
    "name": "Room",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A105",
    "blockName": "A-Block"
  },
  "A202": {
    "id": "A202",
    "name": "Office",
    "parentBuilding": "ABlock",
    "floor": 1,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Office",
    "blockName": "A-Block"
  },
  "A204": {
    "id": "A204",
    "name": "Cashier Section",
    "parentBuilding": "ABlock",
    "floor": 1,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Cashier Section",
    "blockName": "A-Block"
  },
  "A108": {
    "id": "A108",
    "name": "Maintenance Department",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Maintenance Depar...",
    "blockName": "A-Block"
  },
  "A301": {
    "id": "A301",
    "name": "Drawing Hall",
    "parentBuilding": "ABlock",
    "floor": 2,
    "roomType": "hall",
    "category": "hall",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Drawing Hall",
    "blockName": "A-Block"
  },
  "A101": {
    "id": "A101",
    "name": "Classroom A101",
    "parentBuilding": "ABlock",
    "floor": 0,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A101",
    "blockName": "A-Block"
  },
  "A102": {
    "id": "A102",
    "name": "Classroom A102",
    "parentBuilding": "ABlock",
    "floor": 0,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A102",
    "blockName": "A-Block"
  },
  "A112": {
    "id": "A112",
    "name": "Classroom A112",
    "parentBuilding": "ABlock",
    "floor": 0,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A112",
    "blockName": "A-Block"
  },
  "A116": {
    "id": "A116",
    "name": "Classroom A116",
    "parentBuilding": "ABlock",
    "floor": 0,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A116",
    "blockName": "A-Block"
  },
  "A117": {
    "id": "A117",
    "name": "Classroom A117",
    "parentBuilding": "ABlock",
    "floor": 0,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A117",
    "blockName": "A-Block"
  },
  "A208": {
    "id": "A208",
    "name": "Classroom A208",
    "parentBuilding": "ABlock",
    "floor": 1,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A208",
    "blockName": "A-Block"
  },
  "A209": {
    "id": "A209",
    "name": "Classroom A209",
    "parentBuilding": "ABlock",
    "floor": 1,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A209",
    "blockName": "A-Block"
  },
  "A214": {
    "id": "A214",
    "name": "Classroom A214",
    "parentBuilding": "ABlock",
    "floor": 1,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A214",
    "blockName": "A-Block"
  },
  "A302": {
    "id": "A302",
    "name": "Classroom A302",
    "parentBuilding": "ABlock",
    "floor": 2,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A302",
    "blockName": "A-Block"
  },
  "A304": {
    "id": "A304",
    "name": "Classroom A304",
    "parentBuilding": "ABlock",
    "floor": 2,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A304",
    "blockName": "A-Block"
  },
  "A311": {
    "id": "A311",
    "name": "Classroom A311",
    "parentBuilding": "ABlock",
    "floor": 2,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A311",
    "blockName": "A-Block"
  },
  "A401": {
    "id": "A401",
    "name": "Classroom A401",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A401",
    "blockName": "A-Block"
  },
  "A402": {
    "id": "A402",
    "name": "Classroom A402",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A402",
    "blockName": "A-Block"
  },
  "A404": {
    "id": "A404",
    "name": "Classroom A404",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A404",
    "blockName": "A-Block"
  },
  "A405": {
    "id": "A405",
    "name": "Classroom A405",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A405",
    "blockName": "A-Block"
  },
  "A407": {
    "id": "A407",
    "name": "Classroom A407",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A407",
    "blockName": "A-Block"
  },
  "A408": {
    "id": "A408",
    "name": "Classroom A408",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A408",
    "blockName": "A-Block"
  },
  "A412": {
    "id": "A412",
    "name": "Classroom A412",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A412",
    "blockName": "A-Block"
  },
  "A413": {
    "id": "A413",
    "name": "Classroom A413",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "A413",
    "blockName": "A-Block"
  },
  "A205": {
    "id": "A205",
    "name": "IQAC",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "cell",
    "category": "cell",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "IQAC",
    "blockName": "A-Block"
  },
  "A106": {
    "id": "A106",
    "name": "Placement Cell",
    "parentBuilding": "ABlock",
    "floor": 3,
    "roomType": "cell",
    "category": "cell",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Placement Cell",
    "blockName": "A-Block"
  },
  "D202": {
    "id": "D202",
    "name": "Classroom D202",
    "parentBuilding": "DBlock",
    "floor": 1,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D202",
    "blockName": "D-Block"
  },
  "D102": {
    "id": "D102",
    "name": "Civil Engineering",
    "parentBuilding": "DBlock",
    "floor": 1,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D102",
    "blockName": "D-Block"
  },
  "D201": {
    "id": "D201",
    "name": "Faculty D201",
    "parentBuilding": "DBlock",
    "floor": 1,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D201",
    "blockName": "D-Block"
  },
  "D206": {
    "id": "D206",
    "name": "Faculty D206",
    "parentBuilding": "DBlock",
    "floor": 1,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D206",
    "blockName": "D-Block"
  },
  "D401": {
    "id": "D401",
    "name": "AI & DS",
    "parentBuilding": "DBlock",
    "floor": 3,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D401",
    "blockName": "D-Block"
  },
  "D104": {
    "id": "D104",
    "name": "COE Office",
    "parentBuilding": "DBlock",
    "floor": 1,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "COE Office",
    "blockName": "D-Block"
  },
  "D207": {
    "id": "D207",
    "name": "COE Valuation Room",
    "parentBuilding": "DBlock",
    "floor": 1,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "COE Valuation Room",
    "blockName": "D-Block"
  },
  "D208": {
    "id": "D208",
    "name": "COE Valuation Room D208",
    "parentBuilding": "DBlock",
    "floor": 1,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "COE Valuation Roo...",
    "blockName": "D-Block"
  },
  "D307": {
    "id": "D307",
    "name": "COE Record Room",
    "parentBuilding": "DBlock",
    "floor": 2,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "COE Record Room",
    "blockName": "D-Block"
  },
  "D308": {
    "id": "D308",
    "name": "COE Record Room D308",
    "parentBuilding": "DBlock",
    "floor": 2,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "COE Record Room D308",
    "blockName": "D-Block"
  },
  "D204": {
    "id": "D204",
    "name": "Classroom D204",
    "parentBuilding": "DBlock",
    "floor": 1,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D204",
    "blockName": "D-Block"
  },
  "D302": {
    "id": "D302",
    "name": "Classroom D302",
    "parentBuilding": "DBlock",
    "floor": 2,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D302",
    "blockName": "D-Block"
  },
  "D303": {
    "id": "D303",
    "name": "Classroom D303",
    "parentBuilding": "DBlock",
    "floor": 2,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D303",
    "blockName": "D-Block"
  },
  "D304": {
    "id": "D304",
    "name": "Classroom D304",
    "parentBuilding": "DBlock",
    "floor": 2,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D304",
    "blockName": "D-Block"
  },
  "D402": {
    "id": "D402",
    "name": "Classroom D402",
    "parentBuilding": "DBlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D402",
    "blockName": "D-Block"
  },
  "D404": {
    "id": "D404",
    "name": "Classroom D404",
    "parentBuilding": "DBlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D404",
    "blockName": "D-Block"
  },
  "D407": {
    "id": "D407",
    "name": "Classroom D407",
    "parentBuilding": "DBlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D407",
    "blockName": "D-Block"
  },
  "D408": {
    "id": "D408",
    "name": "Classroom D408",
    "parentBuilding": "DBlock",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "D408",
    "blockName": "D-Block"
  },
  "D101": {
    "id": "D101",
    "name": "Exam Cell",
    "parentBuilding": "DBlock",
    "floor": 3,
    "roomType": "cell",
    "category": "cell",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Exam Cell",
    "blockName": "D-Block"
  },
  "E104": {
    "id": "E104",
    "name": "Digital Electronics",
    "parentBuilding": "E-Block",
    "floor": 0,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "DE-Lab",
    "blockName": "E-Block"
  },
  "E106": {
    "id": "E106",
    "name": "Store Room",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Store Room",
    "blockName": "E-Block"
  },
  "E107": {
    "id": "E107",
    "name": "Power Room",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Power Room",
    "blockName": "E-Block"
  },
  "E204": {
    "id": "E204",
    "name": "Power Electronics and Drivers lab / Measurements and instrumentation",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "PEDMI-Lab",
    "blockName": "E-Block"
  },
  "E206": {
    "id": "E206",
    "name": "Power System Simulation Lab",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "PSS-Lab",
    "blockName": "E-Block"
  },
  "E209": {
    "id": "E209",
    "name": "Control Systems Lab/ Linear Integrated Circuits",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "CSLIC-Lab",
    "blockName": "E-Block"
  },
  "E210": {
    "id": "E210",
    "name": "Lab View Academy",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "VA-Lab",
    "blockName": "E-Block"
  },
  "E304": {
    "id": "E304",
    "name": "ELECTRIC CIRCUITS LABORATORY",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "EC-Lab",
    "blockName": "E-Block"
  },
  "E305": {
    "id": "E305",
    "name": "MICROPROCESSORS AND MICROCONTROLLERS LABORATORY",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "MPC-Lab",
    "blockName": "E-Block"
  },
  "E308": {
    "id": "E308",
    "name": "ELECTRONIC DEVICES AND CIRCUITS LABORATORY -I",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "EDC-Lab",
    "blockName": "E-Block"
  },
  "E309": {
    "id": "E309",
    "name": "PROJECT / RESEARCH LABORATORY",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Research-Lab",
    "blockName": "E-Block"
  },
  "E404": {
    "id": "E404",
    "name": "ELECTRONIC DEVICES AND CIRCUITS LABORATORY -II",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "EDC-Lab",
    "blockName": "E-Block"
  },
  "E407": {
    "id": "E407",
    "name": "VLSI / DSP LABORATORY",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "VLSI-Lab",
    "blockName": "E-Block"
  },
  "E408": {
    "id": "E408",
    "name": "MICROWAVE / OPTICAL LABORATORY",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "M/O-Lab",
    "blockName": "E-Block"
  },
  "E409": {
    "id": "E409",
    "name": "COMMUNICATION LABORATORY",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Comm-Lab",
    "blockName": "E-Block"
  },
  "E504": {
    "id": "E504",
    "name": "LIC / DIGITAL LABORATORY",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "LIC-Lab",
    "blockName": "E-Block"
  },
  "E506": {
    "id": "E506",
    "name": "NETWORKS LABORATORY",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "lab",
    "category": "lab",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Networks-Lab",
    "blockName": "E-Block"
  },
  "E105": {
    "id": "E105",
    "name": "Cyber Security Faculty Room",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E105",
    "blockName": "E-Block"
  },
  "E108": {
    "id": "E108",
    "name": "Cyber Security Faculty Room E108",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E108",
    "blockName": "E-Block"
  },
  "E109": {
    "id": "E109",
    "name": "Cyber Security Faculty Room E109",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E109",
    "blockName": "E-Block"
  },
  "E211": {
    "id": "E211",
    "name": "EEE HoD Cabin",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E211",
    "blockName": "E-Block"
  },
  "E205": {
    "id": "E205",
    "name": "Faculty E205",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E205",
    "blockName": "E-Block"
  },
  "E208": {
    "id": "E208",
    "name": "Faculty E208",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E208",
    "blockName": "E-Block"
  },
  "E310": {
    "id": "E310",
    "name": "ECE HoD Cabin",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E310",
    "blockName": "E-Block"
  },
  "E306": {
    "id": "E306",
    "name": "ECE Faculty Room",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E306",
    "blockName": "E-Block"
  },
  "E307-B": {
    "id": "E307-B",
    "name": "ECE Faculty Room E307-B",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E307-B",
    "blockName": "E-Block"
  },
  "E307-C": {
    "id": "E307-C",
    "name": "ECE Faculty Room E307-C",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E307-C",
    "blockName": "E-Block"
  },
  "E311-B": {
    "id": "E311-B",
    "name": "ECE Faculty Room E311-B",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E311-B",
    "blockName": "E-Block"
  },
  "E417": {
    "id": "E417",
    "name": "Room",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E417",
    "blockName": "E-Block"
  },
  "E405": {
    "id": "E405",
    "name": "Faculty Room E405",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E405",
    "blockName": "E-Block"
  },
  "E410": {
    "id": "E410",
    "name": "Faculty Room E410",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E410",
    "blockName": "E-Block"
  },
  "E411": {
    "id": "E411",
    "name": "Faculty Room E411",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E411",
    "blockName": "E-Block"
  },
  "E412": {
    "id": "E412",
    "name": "Faculty Room E412",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E412",
    "blockName": "E-Block"
  },
  "E413": {
    "id": "E413",
    "name": "Faculty Room E413",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E413",
    "blockName": "E-Block"
  },
  "E416": {
    "id": "E416",
    "name": "Faculty Room E416",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E416",
    "blockName": "E-Block"
  },
  "E505": {
    "id": "E505",
    "name": "ETE Faculty Room",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E505",
    "blockName": "E-Block"
  },
  "E510": {
    "id": "E510",
    "name": "ETE Faculty Room E510",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E510",
    "blockName": "E-Block"
  },
  "E511": {
    "id": "E511",
    "name": "ETE Faculty Room E511",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "faculty",
    "category": "faculty",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E511",
    "blockName": "E-Block"
  },
  "E207": {
    "id": "E207",
    "name": "UPS Room",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "UPS Room",
    "blockName": "E-Block"
  },
  "E212": {
    "id": "E212",
    "name": "Department Library (EEE)",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Department Librar...",
    "blockName": "E-Block"
  },
  "E311-A": {
    "id": "E311-A",
    "name": "ECE Store Room",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "ECE Store Room",
    "blockName": "E-Block"
  },
  "E307-A": {
    "id": "E307-A",
    "name": "ECE Meeting and Counseling Room",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "ECE Meeting and C...",
    "blockName": "E-Block"
  },
  "E414": {
    "id": "E414",
    "name": "ECE Department Library",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "ECE Department Li...",
    "blockName": "E-Block"
  },
  "E406": {
    "id": "E406",
    "name": "ECE Store Room II",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "office",
    "category": "office",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "ECE Store Room II",
    "blockName": "E-Block"
  },
  "E512": {
    "id": "E512",
    "name": "ECE Seminar Hall",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "hall",
    "category": "hall",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "ECE Seminar Hall",
    "blockName": "E-Block"
  },
  "E101": {
    "id": "E101",
    "name": "Classroom E101",
    "parentBuilding": "E-Block",
    "floor": 0,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E101",
    "blockName": "E-Block"
  },
  "E102": {
    "id": "E102",
    "name": "Classroom E102",
    "parentBuilding": "E-Block",
    "floor": 0,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E102",
    "blockName": "E-Block"
  },
  "E103": {
    "id": "E103",
    "name": "Classroom E103",
    "parentBuilding": "E-Block",
    "floor": 0,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E103",
    "blockName": "E-Block"
  },
  "E201": {
    "id": "E201",
    "name": "Classroom E201",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E201",
    "blockName": "E-Block"
  },
  "E202": {
    "id": "E202",
    "name": "Classroom E202",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E202",
    "blockName": "E-Block"
  },
  "E203": {
    "id": "E203",
    "name": "Classroom E203",
    "parentBuilding": "E-Block",
    "floor": 1,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E203",
    "blockName": "E-Block"
  },
  "E301": {
    "id": "E301",
    "name": "Classroom E301",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E301",
    "blockName": "E-Block"
  },
  "E302": {
    "id": "E302",
    "name": "Classroom E302",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E302",
    "blockName": "E-Block"
  },
  "E303": {
    "id": "E303",
    "name": "Classroom E303",
    "parentBuilding": "E-Block",
    "floor": 2,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E303",
    "blockName": "E-Block"
  },
  "E401": {
    "id": "E401",
    "name": "Classroom E401",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E401",
    "blockName": "E-Block"
  },
  "E402": {
    "id": "E402",
    "name": "Classroom E402",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E402",
    "blockName": "E-Block"
  },
  "E403": {
    "id": "E403",
    "name": "Classroom E403",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E403",
    "blockName": "E-Block"
  },
  "E415": {
    "id": "E415",
    "name": "Classroom E415",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E415",
    "blockName": "E-Block"
  },
  "E418": {
    "id": "E418",
    "name": "Classroom E418",
    "parentBuilding": "E-Block",
    "floor": 3,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E418",
    "blockName": "E-Block"
  },
  "E501": {
    "id": "E501",
    "name": "Classroom E501",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E501",
    "blockName": "E-Block"
  },
  "E502": {
    "id": "E502",
    "name": "Classroom E502",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E502",
    "blockName": "E-Block"
  },
  "E503": {
    "id": "E503",
    "name": "Classroom E503",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E503",
    "blockName": "E-Block"
  },
  "E507": {
    "id": "E507",
    "name": "Classroom E507",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E507",
    "blockName": "E-Block"
  },
  "E508": {
    "id": "E508",
    "name": "Classroom E508",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E508",
    "blockName": "E-Block"
  },
  "E509": {
    "id": "E509",
    "name": "Classroom E509",
    "parentBuilding": "E-Block",
    "floor": 4,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E509",
    "blockName": "E-Block"
  },
  "E601": {
    "id": "E601",
    "name": "Classroom E601",
    "parentBuilding": "E-Block",
    "floor": 5,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E601",
    "blockName": "E-Block"
  },
  "E602": {
    "id": "E602",
    "name": "Classroom E602",
    "parentBuilding": "E-Block",
    "floor": 5,
    "roomType": "classroom",
    "category": "classroom",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "E602",
    "blockName": "E-Block"
  },
  "E311": {
    "id": "E311",
    "name": "Karpagam Innovation Centre",
    "parentBuilding": "E-Block",
    "floor": 5,
    "roomType": "cell",
    "category": "cell",
    "type": "indoor",
    "opens": 9,
    "closes": 17,
    "shortName": "Karpagam Innovati...",
    "blockName": "E-Block"
  },
};